production:
  server: "https://chatrooomz-private-pub.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: "bdddb290b130fab3e02654f64f8571c3ee56d621980abbaf6997c567a1255fbe"
  signature_expiration: 3600 # one day
